AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
Metrics/AbcSize:
  Max: 30